name: Deploy Portfolio a AWS

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch: 

permissions:
  id-token: write 
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Rayos X al Token OIDC
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = Buffer.from(token.split('.')[1], 'base64').toString();
            console.log("=== LO QUE GITHUB ENVÍA A AWS ===");
            console.log(JSON.parse(payload));

      - name: Autenticarse en AWS con OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::625738166197:role/portfolio-github-actions-deploy
          aws-region: eu-west-1

      - name: Subir archivos web a S3
        run: aws s3 sync ./web/ s3://marcoaavila-portfolio-web --delete

      - name: Invalidar caché de CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3LAZND9ZIMTZK --paths "/*"